# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"
    - "**/generated_plugin_registrant.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Code Style (팀 일관성을 위한 규칙들)
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true

    # Documentation (협업을 위한 문서화)
    public_member_api_docs: true
    lines_longer_than_80_chars: true

    # Performance & Best Practices
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    avoid_function_literals_in_foreach_calls: true
    prefer_collection_literals: true
    prefer_spread_collections: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true

    # Error Prevention
    always_declare_return_types: true
    avoid_catching_errors: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true

    # Formatting
    curly_braces_in_flow_control_structures: true
    always_put_control_body_on_new_line: true

    # Import/Export
    directives_ordering: true
    prefer_relative_imports: true

    # Widgets
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true

    # Flutter specific
    flutter_style_todos: true
    no_logic_in_create_state: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
