name: Auto Assign PR

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    name: Auto Assign PR Author
    runs-on: ubuntu-latest
    
    steps:
      - name: Auto assign PR author
        uses: toshimaru/auto-author-assign@v2.1.1